server.port=8082
server.servlet.context-path=/test
# Enable/disable Swagger UI
swagger.enabled=true

# Application name
app.name=testspring-boot:

# Logging configuration
logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG

#Data Paths
user.data.file=C://Users/ponurko/Documents/data/usersData.json
book.data.file=C://Users/ponurko/Documents/data/booksData.json
vendor.data.file=C://Users/ponurko/Documents/data/vendorsData.json
product.data.file=C://Users/ponurko/Documents/data/productsData.json
order.data.file=C://Users/ponurko/Documents/data/ordersData.json
orderDetail.data.file=C://Users/ponurko/Documents/data/orderDetailsData.json
#Email
own.email=ponurkoalla264@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ponurkoalla264@gmail.com
spring.mail.password=password2024&
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JDBC URL
spring.datasource.url=jdbc:postgresql://localhost:5432/myTest
# login and password for db
spring.datasource.username=postgres
spring.datasource.password=postgres
# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
# Strategy of generation (automatic table creation)
spring.jpa.hibernate.ddl-auto=update
# Dialect Hibernate for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect