server.port=8082
server.servlet.context-path=/test
# Enable/disable Swagger UI
swagger.enabled=true

# Application name
app.name=testspring-boot:

# Logging configuration
logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG

# location definition
warehouse.location.min=1
warehouse.location.max=20
#time of expired orders
cleanUpOrderService.time.of.expired=30
#Data Paths
user.data.file=C://Users/ponurko/Documents/data/usersData.json
book.data.file=C://Users/ponurko/Documents/data/booksData.json
vendor.data.file=C://Users/ponurko/Documents/data/vendorsData.json
product.data.file=C://Users/ponurko/Documents/data/productsData.json
order.data.file=C://Users/ponurko/Documents/data/ordersData.json
orderDetail.data.file=C://Users/ponurko/Documents/data/orderDetailsData.json
#Email by SMTP
spring.mail.host=smtp.mailtrap.io
spring.mail.port=465
spring.mail.username=12cc3a2128bfaf
spring.mail.password=9b8d7cbc01377f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#send email by API
#inbox Id
inboxId=3536037
# my own email
own.email=myTestEmail@gmail.com
# base url
mailtrapClient.base.url=https://sandbox.api.mailtrap.io/api
# api token
mailtrapClient.api.token=0beff163ac22990e5d40d13ffc32bd14

# JDBC URL
spring.datasource.url=jdbc:postgresql://localhost:5432/myTest
# login and password for db
spring.datasource.username=postgres
spring.datasource.password=postgres
# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
# Strategy of generation (automatic table creation)
spring.jpa.hibernate.ddl-auto=update
# Dialect Hibernate for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect